'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useData } from './provider';
import { Heading, Button, Card, Search, Badge, Empty, Notice } from './ui';
import { Icon } from './icons';
import { customerForm, driverForm, truckForm, maintenanceForm } from './forms';
import { dateKey, isOpen, dateTime } from '../shared/format';
export function Customers() { const { data: s, run, openForm } = useData(); const [q, setQ] = useState(''); const list = s.customers.filter(c => `${c.name} ${c.contact} ${c.phone} ${c.document ?? ''}`.toLowerCase().includes(q.toLowerCase())); return <div className="screen enter"><Heading title="Clientes" description="Contratantes, contatos e histórico de locações em um só lugar."><Button variant="primary" icon="plus" onClick={() => openForm(customerForm(run))}>Novo cliente</Button></Heading><Card><div className="toolbar"><Search value={q} onChange={setQ} placeholder="Buscar nome, telefone ou documento..."/><small className="muted">{list.length} cliente(s)</small></div>{list.length ? <div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Responsável</th><th>Contato</th><th>Locações abertas</th><th>Status</th><th /></tr></thead><tbody>{list.map(c => <tr key={c.id}><td><strong>{c.name}</strong><small>{c.document || 'Documento não informado'}</small></td><td>{c.contact}</td><td><a href={`tel:+55${c.phone}`}>{c.phone}</a><small>{c.email || 'Sem e-mail'}</small></td><td><Link className="text-button" href={`/locacoes?busca=${encodeURIComponent(c.name)}`}>{s.rentals.filter(r => r.customerId === c.id && isOpen(r.status)).length} em aberto <Icon name="arrow" size={13}/></Link></td><td><Badge status={c.active ? 'AVAILABLE' : 'RETIRED'} label={c.active ? 'Ativo' : 'Inativo'}/></td><td><Button small icon="edit" onClick={() => openForm(customerForm(run, c))}>Editar</Button></td></tr>)}</tbody></table></div> : <Empty title="Cadastre seu primeiro cliente" description="Informe o contratante e o contato responsável antes de agendar uma locação." icon="users"/>}</Card></div>; }
export function Drivers() { const { data: s, run, openForm } = useData(); const [q, setQ] = useState(''); const list = s.drivers.filter(d => `${d.name} ${d.phone}`.toLowerCase().includes(q.toLowerCase())); return <div className="screen enter"><Heading title="Motoristas" description="Responsáveis pelas entregas e retiradas, com cadastro separado dos acessos ao sistema."><Button variant="primary" icon="plus" onClick={() => openForm(driverForm(run))}>Novo motorista</Button></Heading><Card><div className="toolbar"><Search value={q} onChange={setQ}/></div>{list.length ? <div className="table-scroll"><table><thead><tr><th>Motorista</th><th>Telefone</th><th>CNH / categoria</th><th>Validade cadastrada</th><th>Serviços pendentes</th><th /></tr></thead><tbody>{list.map(d => <tr key={d.id}><td><strong>{d.name}</strong><small>{d.active ? 'Cadastro ativo' : 'Cadastro inativo'}</small></td><td>{d.phone}</td><td>{d.license}<small>Categoria {d.category}</small></td><td><Badge status={d.licenseExpiry && d.licenseExpiry >= dateKey() ? 'AVAILABLE' : 'OVERDUE'} label={d.licenseExpiry?.split('-').reverse().join('/') ?? 'Não informada'}/></td><td>{s.jobs.filter(j => j.driverId === d.id && !['DONE', 'CANCELLED'].includes(j.status)).length}</td><td><Button small icon="edit" onClick={() => openForm(driverForm(run, d))}>Editar</Button></td></tr>)}</tbody></table></div> : <Empty title="Cadastre sua equipe" description="Cadastre os motoristas reais e confira suas habilitações." icon="driver"/>}</Card><Notice>O sistema confere os dados cadastrados; não consulta órgãos oficiais nem valida autenticidade da CNH. Para permitir o acesso do motorista, o administrador deve criar uma conta em Usuários e acessos.</Notice></div>; }
export function Fleet() { const { data: s, run, openForm, openDetail } = useData(); return <div className="screen enter"><Heading title="Frota de caminhões" description="Disponibilidade, equipe e serviços em andamento de cada veículo."><Button icon="plus" variant="primary" onClick={() => openForm(truckForm(run))}>Adicionar caminhão</Button></Heading><div className="fleet-grid">{s.trucks.map(t => { const job = s.jobs.find(j => j.truckId === t.id && ['IN_PROGRESS', 'RETURNING'].includes(j.status)); const next = s.jobs.find(j => j.truckId === t.id && j.status === 'SCHEDULED'); return <Card key={t.id}><div className="fleet-card"><div className="row split"><span className="icon-tile yellow"><Icon name="truck" size={26}/></span><Badge status={job ? 'IN_PROGRESS' : t.status} label={job ? 'Em operação' : undefined}/></div><h2>{t.code}</h2><div className="vehicle-plate">{t.plate ?? 'PLACA A CADASTRAR'}</div><p className="muted">{t.model || 'Modelo ainda não informado'}</p>{job ? <div className="fleet-current"><strong>Serviço em andamento</strong><p>{s.drivers.find(d => d.id === job.driverId)?.name}</p><Button small onClick={() => openDetail(job.rentalId)}>Abrir operação</Button></div> : next ? <div className="fleet-current"><strong>Próximo serviço</strong><p>{dateTime(next.scheduledAt)}</p><small>{s.drivers.find(d => d.id === next.driverId)?.name}</small></div> : <div className="fleet-current muted">Nenhum serviço pendente.</div>}<div className="row wrap"><Button icon="edit" small onClick={() => openForm(truckForm(run, t))}>Editar caminhão</Button>{t.status === 'AVAILABLE' && <Button small icon="tool" onClick={() => openForm(maintenanceForm(s, run, undefined, `truck:${t.id}`))}>Manutenção</Button>}</div></div></Card>; })}</div><Notice>Os dois caminhões iniciais aguardam suas placas reais. A agenda bloqueia sobreposições por motorista e por caminhão. O deslocamento e o retorno devem ser considerados na janela de cada serviço.</Notice></div>; }
