'use client';
import Link from 'next/link';
import { useData } from './provider';
import { Stat, Card, Badge, Button, Empty, Notice } from './ui';
import { Icon } from './icons';
import { rentalForm } from './forms';
import { dateKey, time, dateTime, isOpen } from '../shared/format';
export function Dashboard() {
    const { data: s, run, openForm, openDetail } = useData();
    const today = dateKey(), now = Date.now(), driver = s.user.role === 'DRIVER';
    const inventory = s.containers.filter(c => c.status === 'INVENTORY').length, available = s.containers.filter(c => c.status === 'AVAILABLE').length, onSite = s.containers.filter(c => c.status === 'ON_SITE').length;
    const overdue = s.rentals.filter(r => ['ACTIVE', 'COLLECTING'].includes(r.status) && Date.parse(r.pickupAt) < now), daily = s.jobs.filter(j => dateKey(j.scheduledAt) === today && j.status !== 'CANCELLED'), upcoming = s.jobs.filter(j => !['DONE', 'CANCELLED'].includes(j.status)).slice(0, 4);
    const portions = [{ label: 'No cliente', value: onSite, color: '#d9a820' }, { label: 'Disponíveis', value: available, color: '#3d7b60' }, { label: 'Reservadas', value: s.containers.filter(c => c.status === 'RESERVED').length, color: '#7593ad' }, { label: 'Em trânsito', value: s.containers.filter(c => ['IN_TRANSIT', 'RETURNING'].includes(c.status)).length, color: '#a18ab8' }, { label: 'Manutenção', value: s.containers.filter(c => c.status === 'MAINTENANCE').length, color: '#c2836d' }, { label: 'A conferir / inativas', value: s.containers.filter(c => ['INVENTORY', 'RETIRED'].includes(c.status)).length, color: '#d9ddd2' }];
    let acc = 0;
    const total = s.containers.length || 1, gradient = portions.map(p => { const start = acc; acc += p.value / total * 100; return `${p.color} ${start}% ${acc}%`; }).join(',');
    return <div className="screen enter"><div className="dashboard-greeting"><div><span className="eyebrow">CENTRAL OPERACIONAL</span><h1>Olá, {s.user.name.split(' ')[0]}. Sua operação em um só lugar.</h1><p>Seu pátio, sua equipe e cada caçamba. Uma visão completa da operação.</p></div><div className="date-chip"><Icon name="calendar" size={16}/>{new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: 'long', year: 'numeric' }).format(new Date())}</div></div>
 <section className="dashboard-hero"><div><span className="eyebrow">DO PÁTIO AO CLIENTE, SEM PERDER O CONTROLE.</span><h2>Cada caçamba no lugar certo.</h2><p>{driver ? 'Confira seus serviços e registre cada etapa quando ela acontecer.' : 'Planeje as entregas. Acompanhe os prazos. Confirme cada retorno.'}</p><div className="row wrap">{!driver && <Button variant="primary" icon="plus" onClick={() => openForm(rentalForm(s, run))}>Nova locação</Button>}<Link className="button dark-secondary" href={driver ? '/minha-rota' : '/agenda'}><Icon name="calendar" size={16}/>Ver programação</Link></div></div><div className="hero-insight"><Icon name="truck" size={45}/><strong>{s.trucks.length.toString().padStart(2, '0')}</strong><span>caminhões na frota{driver ? ' atribuída' : ''}</span><small>{s.jobs.filter(j => ['IN_PROGRESS', 'RETURNING'].includes(j.status)).length} serviço(s) em andamento</small></div></section>
 <div className="stats-grid"><Stat label={driver ? 'Caçambas vinculadas' : 'Total de caçambas'} value={s.containers.length} caption={inventory ? `${inventory} aguardam conferência` : 'Inventário identificado individualmente'} icon="bin"/><Stat label="Disponíveis no pátio" value={available} caption="Conferidas e liberadas para locação" icon="check" tone="green"/><Stat label="No cliente" value={onSite} caption="Inclui retiradas em andamento" icon="pin" tone="blue"/><Stat label="Retiradas atrasadas" value={overdue.length} caption="Prazo previsto vencido, sem coleta" icon="clock" tone={overdue.length ? 'red' : 'neutral'}/></div>
 {!driver && (!s.settings.yardAddress || inventory > 0 || s.trucks.some(t => !t.plate) || !s.drivers.length) && <Notice tone="warning"><strong>Finalize a implantação.</strong> Cadastre o pátio, as placas reais e os motoristas. Confira as caçambas no pátio ou registre as que já estão em clientes. {s.user.role === 'ADMIN' && <Link className="text-button" href="/configuracoes">Ver checklist <Icon name="arrow" size={14}/></Link>}</Notice>}
 <div className="dashboard-middle"><Card title="Distribuição das caçambas" subtitle="Situação física e disponibilidade" action={<Link className="text-button" href="/mapa">Ver mapa <Icon name="arrow" size={14}/></Link>}><div className="distribution-content"><div className="donut-chart" style={{ background: `conic-gradient(${gradient})` }} role="img" aria-label={portions.map(p => `${p.label}: ${p.value}`).join(', ')}><div><strong>{s.containers.length}</strong><small>CAÇAMBAS</small></div></div><div className="chart-legend">{portions.map(p => <div className="legend-row" key={p.label}><span style={{ background: p.color }}/><small>{p.label}</small><strong>{p.value}</strong></div>)}</div></div></Card>
 <Card title="Próximos serviços" subtitle={`${daily.length} serviço(s) programado(s) para hoje`} action={<Link className="text-button" href={driver ? '/minha-rota' : '/agenda'}>Ver agenda <Icon name="arrow" size={14}/></Link>}>{upcoming.length ? <div className="upcoming-list">{upcoming.map(j => { const r = s.rentals.find(r => r.id === j.rentalId)!; return <button className="upcoming-item" key={j.id} onClick={() => openDetail(r.id)}><div className="time-box"><strong>{time(j.scheduledAt)}</strong><small>{dateKey(j.scheduledAt) === today ? 'HOJE' : dateKey(j.scheduledAt).split('-').slice(1).reverse().join('/')}</small></div><div className="upcoming-main"><strong>{s.containers.find(c => c.id === r.containerId)?.code} <span>/ {s.customers.find(c => c.id === r.customerId)?.name}</span></strong><small>{r.neighborhood} · {r.city}</small></div><Badge status={j.kind}/><Icon name="chevron" size={14}/></button>; })}</div> : <Empty title="Agenda livre" description="Novos serviços de entrega e retirada aparecerão aqui." icon="calendar"/>}</Card></div>
 <div className="dashboard-bottom"><Card title="Atenção aos prazos" subtitle="Locações que precisam de acompanhamento">{overdue.length ? overdue.slice(0, 5).map(r => <button className="alert-item" key={r.id} onClick={() => openDetail(r.id)}><span className="icon-tile red"><Icon name="clock"/></span><div><strong>{s.containers.find(c => c.id === r.containerId)?.code} · {r.neighborhood}</strong><small>Retirada prevista: {dateTime(r.pickupAt)}</small></div><Icon name="arrow" size={15}/></button>) : <Empty title="Nenhuma retirada atrasada" description="Os prazos de retirada estão em dia neste momento." icon="check"/>}</Card><Card title="Atividade recente" subtitle="Registros efetivos da operação">{s.events.length ? <div className="activity-list">{s.events.slice(0, 4).map(e => <button key={e.id} className="activity-item" onClick={() => openDetail(e.rentalId)}><span className="activity-dot"/><div><strong>{s.rentals.find(r => r.id === e.rentalId)?.code}</strong><p>{e.description}</p><small>{e.actorName} · {dateTime(e.occurredAt)}</small></div></button>)}</div> : <Empty title="O histórico começa aqui" description="Entregas, retiradas e alterações serão registradas com data e responsável." icon="history"/>}</Card></div></div>;
}
