import type { Snapshot, Container, Customer, Driver, Truck, Job, Rental, Maintenance, Payment } from '../shared/types';
import { toLocalInput, fromLocalInput, cents, LABEL, ROLE_LABEL } from '../shared/format';
import { received } from '../shared/reports';
import type { Run } from './provider';
import type { FormConfig, Field } from './form-dialog';
import { resolveCoordinates } from '../shared/geo';
const option = (value: string, label: string) => ({ value, label });
const text = (name: string, label: string, required = true): Field => ({ name, label, required });
const select = (name: string, label: string, options: {
    value: string;
    label: string;
}[], required = true): Field => ({ name, label, type: 'select', options, required });
const notes: Field = { name: 'notes', label: 'Observações', type: 'textarea', full: true };
const GPS: Field[] = [{ name: 'latitude', label: 'Latitude (opcional)', type: 'number', min: -90, max: 90, hint: 'Preenchida pelo CEP ou pelo endereço em Taboão da Serra e Embu das Artes.' }, { name: 'longitude', label: 'Longitude (opcional)', type: 'number', min: -180, max: 180 }];
const stateOptions = [option('1', 'Ativo'), option('0', 'Inativo')];
const driverOptions = (s: Snapshot) => s.drivers.filter(d => d.active).map(d => option(d.id, d.name));
const truckOptions = (s: Snapshot) => s.trucks.filter(t => t.status === 'AVAILABLE').map(t => option(t.id, `${t.code} ${t.plate ?? '(cadastre a placa)'}`));
export function rentalForm(s: Snapshot, run: Run, opening = false, binId?: string): FormConfig {
    const delivery = new Date(Math.ceil(Date.now() / 3600000) * 3600000 + 3600000), pickup = new Date(delivery.getTime() + s.settings.defaultDays * 86400000);
    return { title: opening ? 'Registrar caçamba já no cliente' : 'Nova locação', description: opening ? 'Abertura da operação: entrega passada declarada, sem simular uma saída feita pelo aplicativo.' : 'A caçamba fica reservada imediatamente. Entrega e retirada têm motorista, caminhão e janela de serviço.', initial: { containerId: binId ?? '', deliveryAt: toLocalInput(opening ? new Date(Date.now() - 86400000) : delivery), pickupAt: toLocalInput(pickup), price: (s.settings.defaultPriceCents / 100).toFixed(2), byMeasurement: false, durationMinutes: s.settings.jobDurationMinutes, wasteType: 'Resíduos de construção', deliveryDriverId: s.drivers.find(d => d.active)?.id ?? '', pickupDriverId: s.drivers.find(d => d.active)?.id ?? '', deliveryTruckId: s.trucks.find(t => t.plate && t.status === 'AVAILABLE')?.id ?? '', pickupTruckId: s.trucks.find(t => t.plate && t.status === 'AVAILABLE')?.id ?? '' }, fields: [
            { ...select('customerId', 'Cliente / contratante', s.customers.filter(c => c.active).map(c => option(c.id, c.name))), group: '01 / Cliente e equipamento' },
            select('containerId', 'Caçamba', s.containers.filter(c => c.status === (opening ? 'INVENTORY' : 'AVAILABLE')).map(c => option(c.id, `${c.code} ${c.capacityM3 ? `· ${c.capacityM3} m³` : ''}`))),
            ...(opening ? [{ name: 'capacityM3', label: 'Capacidade real (m³)', type: 'number', required: true, min: 0.5, max: 50 } as Field] : []),
            { ...text('postalCode', 'CEP', false), group: '02 / Local de entrega', hint: 'Ao informar o CEP, o bairro e a cidade são preenchidos automaticamente.' },
            { ...text('address', 'Rua, número e complemento'), full: true }, text('neighborhood', 'Bairro'), { ...text('city', 'Cidade / UF'), hint: 'Área de operação: Taboão da Serra e Embu das Artes.' }, text('siteContact', 'Responsável no local'), { ...text('sitePhone', 'Telefone no local'), type: 'tel' }, text('wasteType', 'Tipo de resíduo'), ...GPS,
            { name: 'deliveryAt', label: opening ? 'Entrega que já aconteceu' : 'Entrega prevista', type: 'datetime-local', required: true, group: '03 / Programação' },
            { name: 'pickupAt', label: 'Retirada prevista', type: 'datetime-local', required: true },
            select('deliveryDriverId', opening ? 'Motorista que entregou' : 'Motorista da entrega', driverOptions(s)), select('deliveryTruckId', 'Caminhão da entrega', truckOptions(s)),
            select('pickupDriverId', 'Motorista da retirada', driverOptions(s)), select('pickupTruckId', 'Caminhão da retirada', truckOptions(s)),
            { name: 'durationMinutes', label: 'Janela por serviço (minutos)', type: 'number', required: true, min: 15, max: 480, step: 15, hint: 'Inclua deslocamento, manobra, descarga e retorno necessários.' },
            { name: 'byMeasurement', label: 'Cobrança por medição', type: 'checkbox', hint: 'Marque se o valor será definido depois da medição no local. O valor contratado deixa de ser obrigatório.' },
            { ...text('price', 'Valor total contratado (R$)'), hint: 'Não altera automaticamente ao reagendar.', when: { field: 'byMeasurement', value: false } }, notes,
            ...(opening ? [{ name: 'confirmed', label: 'Conferi que esta caçamba já está neste cliente e que a entrega informada é verdadeira.', type: 'checkbox', required: true } as Field] : [])
        ],
        submit: async (p) => {
            const point = await resolveCoordinates(p);
            const measured = p.byMeasurement === true;
            const result = await run(opening ? 'importActiveRental' : 'createRental', { ...p, ...(point ? { latitude: point.lat, longitude: point.lon } : {}), deliveryAt: fromLocalInput(String(p.deliveryAt)), pickupAt: fromLocalInput(String(p.pickupAt)), byMeasurement: measured, priceCents: measured ? 0 : cents(String(p.price ?? '')) });
            return result;
        }, submitLabel: opening ? 'Registrar abertura' : 'Agendar locação' };
}
export function customerForm(run: Run, c?: Customer): FormConfig { return { title: c ? 'Editar cliente' : 'Novo cliente', initial: c ? { ...c, active: String(c.active) } : { active: '1' }, fields: [text('name', 'Nome / razão social'), text('contact', 'Responsável pela contratação'), { ...text('phone', 'Telefone com DDD'), type: 'tel' }, { ...text('email', 'E-mail', false), type: 'email' }, text('document', 'CPF / CNPJ (opcional)', false), select('active', 'Cadastro', stateOptions), { ...text('postalCode', 'CEP', false), hint: 'Ao informar o CEP, o endereço cadastral é preenchido automaticamente.' }, { ...text('address', 'Endereço cadastral', false), full: true }, notes], submit: p => run(c ? 'updateCustomer' : 'createCustomer', { ...p, ...(c ? { id: c.id } : {}), active: Number(p.active) }) }; }
export function driverForm(run: Run, d?: Driver): FormConfig { return { title: d ? 'Editar motorista' : 'Novo motorista', description: 'Confira a documentação e a categoria compatível com cada veículo. Este cadastro não cria acesso ao sistema.', initial: d ? { ...d, active: String(d.active) } : { active: '1' }, fields: [text('name', 'Nome completo'), { ...text('phone', 'Telefone com DDD'), type: 'tel' }, text('license', 'Número da CNH'), select('category', 'Categoria da CNH', ['C', 'D', 'E'].map(c => option(c, c))), { name: 'licenseExpiry', label: 'Validade da CNH', type: 'date', required: true }, select('active', 'Cadastro', stateOptions)], submit: p => run(d ? 'updateDriver' : 'createDriver', { ...p, ...(d ? { id: d.id } : {}), active: Number(p.active) }) }; }
export function truckForm(run: Run, t?: Truck): FormConfig { return { title: t ? 'Editar caminhão' : 'Novo caminhão', initial: t ? { ...t } : { status: 'AVAILABLE' }, fields: [text('code', 'Identificação interna'), text('plate', 'Placa real', false), text('model', 'Modelo / descrição', false), ...(t?.status === 'MAINTENANCE' ? [] : [select('status', 'Disponibilidade', [option('AVAILABLE', 'Disponível'), option('RETIRED', 'Inativo')])]), notes], submit: p => run(t ? 'updateTruck' : 'createTruck', { ...p, ...(t ? { id: t.id } : {}), ...(t?.status === 'MAINTENANCE' ? { status: undefined } : {}) }) }; }
export function containerForm(run: Run, c?: Container): FormConfig { return { title: c ? `Editar ${c.code}` : 'Nova caçamba', description: 'A disponibilidade muda pela conferência e pelo ciclo operacional, nunca por uma troca manual de status.', initial: c ? { ...c } : {}, fields: [text('code', 'Código de identificação'), { name: 'capacityM3', label: 'Capacidade real (m³)', type: 'number', min: 0.5, max: 50 }, notes], submit: p => run(c ? 'updateContainer' : 'createContainer', { ...p, ...(c ? { id: c.id } : {}) }) }; }
export function inventoryForm(s: Snapshot, run: Run, id?: string): FormConfig { return { title: 'Conferir caçambas no pátio', description: 'Selecione apenas caçambas fisicamente presentes, vazias e aptas. Faça lotes separados por capacidade.', initial: { ids: id ? [id] : [] }, fields: [{ name: 'ids', label: 'Caçambas aguardando conferência', type: 'multi', options: s.containers.filter(c => c.status === 'INVENTORY').map(c => option(c.id, c.code)), full: true }, { name: 'capacityM3', label: 'Capacidade real deste lote (m³)', type: 'number', required: true, min: 0.5, max: 50 }, { name: 'confirmed', label: 'Conferi presencialmente que todas as selecionadas estão vazias, aptas e no pátio.', type: 'checkbox', required: true }], submit: p => run('confirmInventory', p), submitLabel: 'Confirmar e liberar' }; }
export function scheduleForm(s: Snapshot, run: Run, j: Job): FormConfig { return { title: `Reagendar ${LABEL[j.kind].toLowerCase()}`, description: 'Preserva o histórico de horários e responsáveis. Não altera o preço contratado.', initial: { ...j, scheduledAt: toLocalInput(j.scheduledAt) }, fields: [{ name: 'scheduledAt', label: 'Novo horário previsto', type: 'datetime-local', required: true }, { name: 'durationMinutes', label: 'Janela de serviço (minutos)', type: 'number', required: true, min: 15, max: 480 }, select('driverId', 'Motorista', driverOptions(s)), select('truckId', 'Caminhão', truckOptions(s)), { name: 'reason', label: 'Motivo do reagendamento', type: 'textarea', required: true, full: true }], submit: p => run('rescheduleJob', { ...p, id: j.id, version: j.version, scheduledAt: fromLocalInput(String(p.scheduledAt)) }) }; }
export function transitionForm(run: Run, r: Rental, action: string): FormConfig {
    const titles: Record<string, string> = { start_delivery: 'Iniciar entrega', complete_delivery: 'Confirmar entrega no local', start_pickup: 'Iniciar retirada', complete_pickup: 'Confirmar coleta no cliente', return_yard: 'Conferir retorno ao pátio', cancel: 'Cancelar locação', abort_delivery: 'Registrar entrega não realizada', abort_pickup: 'Registrar retirada não realizada' };
    const abort = action.startsWith('abort'), reason = abort || action === 'cancel';
    return { title: titles[action], description: action === 'return_yard' ? 'Confirme que a caçamba retornou, foi descarregada e inspecionada. Somente então ela poderá ser reutilizada.' : action === 'complete_pickup' ? 'A coleta não libera a caçamba. Ela permanecerá retornando até a conferência no pátio.' : 'Registre esta etapa somente quando ela acontecer. O horário real será registrado pelo servidor.', initial: action === 'return_yard' ? { condition: 'GOOD' } : {}, fields: [...(action === 'complete_delivery' ? [text('receiver', 'Nome de quem recebeu a caçamba')] : []), ...(action === 'return_yard' ? [select('condition', 'Condição após a inspeção', [option('GOOD', 'Vazia, conferida e apta para uso'), option('MAINTENANCE', 'Necessita manutenção')])] : []), { ...notes, label: reason ? 'Motivo / ocorrência' : 'Observações da operação', required: reason }, ...(abort ? [{ name: 'returnConfirmed', label: 'O caminhão retornou ao pátio. A caçamba voltou reservada (entrega) ou continua no cliente (retirada).', type: 'checkbox', required: true } as Field] : []), ...(action !== 'cancel' ? GPS : [])], gps: action !== 'cancel', submit: p => run('transitionRental', { ...p, id: r.id, version: r.version, action }), submitLabel: 'Confirmar operação' };
}
export function paymentForm(s: Snapshot, run: Run, r: Rental): FormConfig { return { title: `Receber / ${r.code}`, description: r.byMeasurement ? 'Locação por medição: informe o valor apurado. Não cria cobrança Pix, transação bancária ou pagamento com cartão.' : 'Lançamento manual. Não cria cobrança Pix, transação bancária ou pagamento com cartão.', initial: { amount: r.byMeasurement ? '' : ((r.priceCents - received(s, r.id)) / 100).toFixed(2), method: 'PIX', paidAt: toLocalInput(new Date()) }, fields: [text('amount', 'Valor recebido (R$)'), select('method', 'Forma de recebimento', ['PIX', 'CASH', 'TRANSFER', 'CARD'].map(m => option(m, LABEL[m]))), { name: 'paidAt', label: 'Data e horário do recebimento', type: 'datetime-local', required: true }, { name: 'note', label: r.byMeasurement ? 'Medição / referência' : 'Referência / observação', type: 'textarea', full: true }], submit: p => run('addPayment', { ...p, rentalId: r.id, amountCents: cents(String(p.amount)), paidAt: fromLocalInput(String(p.paidAt)) }) }; }
export function voidForm(run: Run, pmt: Payment): FormConfig { return { title: 'Estornar registro de recebimento', description: 'Apenas o lançamento interno será estornado. A devolução do dinheiro deve ser feita fora do sistema.', fields: [{ name: 'reason', label: 'Motivo do estorno', type: 'textarea', required: true, full: true }], submit: p => run('voidPayment', { ...p, id: pmt.id }) }; }
export function maintenanceForm(s: Snapshot, run: Run, m?: Maintenance, resourceId?: string): FormConfig {
    return m ? { title: 'Concluir manutenção', initial: { cost: (m.costCents / 100).toFixed(2) }, fields: [{ name: 'resolution', label: 'Reparo e inspeção realizados', type: 'textarea', required: true, full: true }, text('cost', 'Custo total (R$)')], submit: p => run('finishMaintenance', { ...p, id: m.id, costCents: cents(String(p.cost)) }) } : { title: 'Abrir manutenção', description: 'O equipamento ficará indisponível até a conclusão do reparo. Caminhões com serviços pendentes precisam ser reatribuídos.', initial: { resourceId: resourceId ?? '', cost: '0.00' }, fields: [select('resourceId', 'Equipamento', [...s.containers.filter(c => c.status === 'AVAILABLE').map(c => option(`container:${c.id}`, c.code)), ...s.trucks.filter(t => t.status === 'AVAILABLE').map(t => option(`truck:${t.id}`, `${t.code} / caminhão`))]), { name: 'description', label: 'Problema / reparo necessário', type: 'textarea', required: true, full: true }, text('cost', 'Custo estimado (R$)')], submit: p => { const [resource, id] = String(p.resourceId).split(':'); return run('startMaintenance', { ...p, resource, resourceId: id, costCents: cents(String(p.cost)) }); } };
}
export function settingsForm(s: Snapshot, run: Run): FormConfig { return { title: 'Configurações da operação', initial: { ...s.settings, price: (s.settings.defaultPriceCents / 100).toFixed(2) }, fields: [text('companyName', 'Nome da empresa'), { ...text('companyPhone', 'Telefone da empresa', false), type: 'tel' }, { ...text('postalCode', 'CEP do pátio', false), hint: 'Ao informar o CEP, o endereço do pátio é preenchido automaticamente.' }, { ...text('yardAddress', 'Endereço completo do pátio'), full: true }, { name: 'defaultDays', label: 'Prazo sugerido de locação (dias)', type: 'number', min: 1, max: 365, required: true }, { name: 'jobDurationMinutes', label: 'Janela sugerida por serviço (minutos)', type: 'number', min: 15, max: 480, required: true }, text('price', 'Valor sugerido de locação (R$)')], submit: p => run('saveSettings', { ...p, defaultPriceCents: cents(String(p.price)) }) }; }
export function userForm(s: Snapshot, run: Run): FormConfig { return { title: 'Novo acesso ao sistema', description: 'O perfil motorista visualiza somente os serviços atribuídos a ele. Compartilhe a senha por um canal privado.', initial: { role: 'DISPATCHER' }, fields: [text('name', 'Nome do usuário'), { ...text('email', 'E-mail de acesso'), type: 'email' }, select('role', 'Perfil', Object.entries(ROLE_LABEL).map(([v, l]) => option(v, l))), { ...select('driverId', 'Vincular motorista', s.drivers.filter(d => d.active && !s.users.some(u => u.driverId === d.id)).map(d => option(d.id, d.name))), when: { field: 'role', value: 'DRIVER' } }, { ...text('password', 'Senha inicial (mínimo 12 caracteres)'), type: 'password', full: true }], submit: p => run('createUser', p) }; }
export function passwordForm(run: Run): FormConfig { return { title: 'Alterar minha senha', description: 'Todas as suas sessões serão encerradas após a alteração.', fields: [{ ...text('currentPassword', 'Senha atual'), type: 'password', full: true }, { ...text('newPassword', 'Nova senha (mínimo 12 caracteres)'), type: 'password', full: true }], submit: p => run('changePassword', p) }; }
